[project]
name = "uniapi"
version = "0.1.0"
description = "LLM Gateway"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.111.0",
  "uvicorn[standard]>=0.30.0",
  "httpx>=0.27.0",
  "pydantic>=2.0.0",
  "litellm>=1.80.7",
]

[tool.uv]
package = false
